
name: Deployment

on:
    push:
        branches:
        - main

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest

        

        steps: 
            - name: Load .env Variable
              run: echo  ${{ env.RAILWAY_TOKEN }}

            - uses: devtomio/action-railway@v1.1.4
              with:
                railway_token: ${{ env.RAILWAY_TOKEN }}

            

